#!/bin/sh

NAME=tlibc

. ./tmake.sh

tmake_init "$@"
echo '
# build for stanix by default
TARGET=stanix

# freestanding environment setup
CFLAGS += -Wall \
	-Wextra \
	-std=gnu99 \
	-fno-stack-protector \
	-fno-stack-check \
	-fno-omit-frame-pointer \
	-nostdlib \
	-ffreestanding \
	-I include \
	-I include/$(TARGET) \
	-D$(ARCH)=1 \
	-D__TLIBC__

KFLAGS = -mcmodel=large -D__LIBK__=1 -Dmalloc=kmalloc -Dfree=kfree -ffreestanding -fno-PIC
ifeq ($(ARCH),x86_64)
	KFLAGS += -mno-sse -mno-sse2 -mno-80387 -mno-80387
endif

#if a file exist in libm/$(ARCH) don'\''t take the generic version in libm/generic
M_ARCH_SRC = $(wildcard libm/$(ARCH)/*.s)
M_SRC = $(M_ARCH_SRC) $(filter-out $(M_ARCH_SRC:libm/$(ARCH)/%.s=libm/generic/%.c),$(wildcard libm/generic/*.c))

DYNFLAGS = -D__DYNAMIC__=1'>> "$MAKEFILE"

# libk target
K_DEPS="errno.c string/memset.c string/memcpy.c string/memchr.c string/memcmp.c string/strcat.c string/strlen.c  string/strnlen.c string/strcpy.c string/strncpy.c string/strcmp.c string/strncmp.c string/strchr.c string/strstr.c string/strncasecmp.c ctype/ctype.c stdio/vsnprintf.c stdio/snprintf.c stdio/vsprintf.c stdio/sprintf.c stdlib/strto.c"
K_SRC=""
for I in $K_DEPS ; do
	K_SRC="$K_SRC libc/$I"
done
tmake_add_static_library "libk" $K_SRC CFLAGS="\$(KFLAGS)"

# ld-tlibc target
# libc objects used by linker
DL_DEPS="tlibc.c auxv.c pthread/uthread.c \$(ARCH)/__get_uthread.s errno.c ctype/ctype.c \
	string/strcmp.c string/strchr.c string/strrchr.c string/strcpy.c string/strlen.c string/strnlen.c \
	string/memset.c string/memcmp.c string/memchr.c string/memcpy.c \
	stdio/vsnprintf.c stdio/vsprintf.c stdio/sprintf.c stdio/fwrite.c stdio/__fileio_write.c stdio/fflush.c \
	stdio/puts.c stdio/putchar.c stdio/fputs.c stdio/fputc.c stdio/stdio.c stdio/vfprintf.c stdio/fprintf.c \
	stdlib/exit.c stdlib/environ.c stdlib/getenv.c"

DL_SRC="$(echo linker/*.c) linker/abi/\$(ARCH)-\$(TARGET).s crt/\$(ARCH)/crt0-\$(TARGET).s \$(shell find libc/\$(TARGET) -name "*.c")"
for I in $DL_DEPS ; do
	DL_SRC="$DL_SRC libc/$I"
done

tmake_add_shared_library "ld-tlibc" $DL_SRC CFLAGS="\$(DYNFLAGS) -D__DL_TLIBC__=1 -fPIC -mgeneral-regs-only -fvisibility=hidden" LDFLAGS="-static-libgcc -Wl,--no-dynamic-linker,-z,now,-soname,ld-tlibc.so,-Bsymbolic,-e,_start"

# libc target
C_SRC_DIR="ctype libgen time stdlib string wchar stdio unistd locale pwd pthread dl"
C_SRC="\$(wildcard libc/\$(TARGET)/*.[cs] libc/\$(TARGET)/*/*.[cs] libc/\$(ARCH)/*.[cs]) $(echo libc/*.c)"

for SRC_DIR in $C_SRC_DIR ; do
	C_SRC="$C_SRC $(find "libc/$SRC_DIR" -name "*.c")"
done

set -f
tmake_add_static_library "libc" $C_SRC HAVE_C=yes HAVE_S=yes
tmake_add_shared_library "libc" $C_SRC CFLAGS="\$(DYNFLAGS)" LDFLAGS="-Wl,-soname,libc.so" DEPENDENCIES="ld-tlibc" HAVE_C=yes HAVE_S=yes

# libm target
tmake_add_library "libm" "\$(M_SRC)" LDFLAGS="-Wl,-soname,libm.so -lgcc_s" DEPENDENCIES="libc" HAVE_C=yes HAVE_S=yes

# stub libs (libdl and libpthread)
tmake_add_static_library "libdl" stub/dl.c CFLAGS="-fno-PIC"
tmake_add_static_library "libpthread" stub/pthread.c CFLAGS="-fno-PIC"

echo "
# headers generations

\$(BUILDDIR)/headers/%.h : include/%.h
	@mkdir -p \"\$(@D)\"
	@echo \"GEN \$@\"
	\$(Q)cat prologue.h \$^ epilogue.h > \$@

\$(BUILDDIR)/headers/%.h : include/\$(TARGET)/%.h
	@mkdir -p \"\$(@D)\"
	@echo \"GEN \$@\"
	\$(Q)cat prologue.h \$^ epilogue.h > \$@

# cdefs contain the guards itself
\$(BUILDDIR)/headers/sys/cdefs.h : include/_cdefs.h
	@mkdir -p \"\$(@D)\"
	@echo \"GEN \$@\"
	\$(Q)cat \$^ > \$@

\$(BUILDDIR)/headers/%/ :
	@mkdir -p \"\$@\"

.PHONY : clean-headers
clean-headers :
	@echo \"CLEAN \$(BUILDDIR)/headers\"
	\$(Q)rm -fr \"\$(BUILDDIR)/headers\"
" >> "$MAKEFILE"

# headers target
set +f
H_SRC=""
for I in include/*.h ; do 
	H_SRC="$H_SRC \$(BUILDDIR)/headers/${I##"include/"}"
done
H_SRC="$H_SRC \$(patsubst include/\$(TARGET)/%,\$(BUILDDIR)/headers/%,\$(wildcard include/\$(TARGET)/*.h include/\$(TARGET)/*/))"

set -f
tmake_add_data "headers" "include" $H_SRC

# src inside directories
echo "
install-headers : \$(patsubst include/\$(TARGET)/%,\$(BUILDDIR)/headers/%,\$(wildcard include/\$(TARGET)/*/*.h)) \$(BUILDDIR)/headers/sys/cdefs.h" >> "$MAKEFILE"

CRTS_SRC="crt/\$(ARCH)/crti.o crt/\$(ARCH)/crtn.o crt/\$(ARCH)/crt0-\$(TARGET).o"
CRTS="\$(BUILDDIR)/crts/crti.o \$(BUILDDIR)/crts/crtn.o \$(BUILDDIR)/crts/crt0.o"

VAR_SETUP="" tmake_add_target "crts" "$CRTS" "lib" $CRT_SRC

echo "
\$(BUILDDIR)/crts/crt%.o : crt/\$(ARCH)/crt%.s
	@mkdir -p \"\$(@D)\"
	@echo \"AS \$<\"
	\$(Q) \$(AS) \$(ASFLAGS) -o \$@ \$<

\$(BUILDDIR)/crts/crt0.o : crt/\$(ARCH)/crt0-\$(TARGET).s
	@mkdir -p \"\$(@D)\"
	@echo \"AS \$<\"
	\$(Q) \$(AS) \$(ASFLAGS) -o \$@ \$<
" >> "$MAKEFILE"

tmake_fini
