#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <libintl.h>

#define N_(str) str

static const char *_error_strings[] = {
	[EPERM] = N_("Operation not permitted"),
	[ENOENT] = N_("No such file or directory"),
	[ESRCH] = N_("No such process"),
	[EINTR] = N_("Interrupted system call"),
	[EIO] = N_("Input/Output error"),
	[ENXIO] = N_("No such device or address"),
	[E2BIG] = N_("Argument list too long"),
	[ENOEXEC] = N_("Exec format error"),
	[EBADF] = N_("Bad file descriptor"),
	[ECHILD] = N_("No child processes"),
	[EAGAIN] = N_("Resource temporarily unavailable"),
	[ENOMEM] = N_("Cannot allocate memory"),
	[EACCES] = N_("Permission denied"),
	[EFAULT] = N_("Bad address"),
	[ENOTBLK] = N_("Block device required"),
	[EBUSY] = N_("Device or resource busy"),
	[EEXIST] = N_("File exists"),
	[EXDEV] = N_("Invalid cross-device link"),
	[ENODEV] = N_("No such device"),
	[ENOTDIR] = N_("Not a directory"),
	[EISDIR] = N_("Is a directory"),
	[EINVAL] = N_("Invalid argument"),
	[ENFILE] = N_("Too many open files in system"),
	[EMFILE] = N_("Too many open files"),
	[ENOTTY] = N_("Inappropriate ioctl for device"),
	[ETXTBSY] = N_("Text file busy"),
	[EFBIG] = N_("File too large"),
	[ENOSPC] = N_("No space left on device"),
	[ESPIPE] = N_("Illegal seek"),
	[EROFS] = N_("Read only file system"),
	[EMLINK] = N_("Too many links"),
	[EPIPE] = N_("Broken pipe"),
	[EDOM] = N_("Math arg out of domain of func"),
	[ERANGE] = N_("Math result not representable"),
	[ENOMSG] = N_("No message of desired type"),
	[EIDRM] = N_("Identifier removed"),
	[ECHRNG] = N_("Channel number out of range"),
	[EL2NSYNC] = N_("Level 2 not synchronized"),
	[EL3HLT] = N_("Level 3 halted"),
	[EL3RST] = N_("Level 3 reset"),
	[ELNRNG] = N_("Link number out of range"),
	[EUNATCH] = N_("Protocol driver not attached"),
	[ENOCSI] = N_("No CSI structure available"),
	[EL2HLT] = N_("Level 2 halted"),
	[EDEADLK] = N_("Deadlock condition"),
	[ENOLCK] = N_("No record locks available"),
	[EBADE] = N_("Invalid exchange"),
	[EBADR] = N_("Invalid request descriptor"),
	[EXFULL] = N_("Exchange full"),
	[ENOANO] = N_("No anode"),
	[EBADRQC] = N_("Invalid request code"),
	[EBADSLT] = N_("Invalid slot"),
	[EDEADLOCK] = N_("File locking deadlock error"),
	[EBFONT] = N_("Bad font file format"),
	[ENOSTR] = N_("Device not a stream"),
	[ENODATA] = N_("No data available"),
	[ETIME] = N_("Timer expired"),
	[ENOSR] = N_("Out of streams resources"),
	[ENONET] = N_("Machine is not on the network"),
	[ENOPKG] = N_("Package not installed"),
	[EREMOTE] = N_("The object is remote"),
	[ENOLINK] = N_("The link has been severed"),
	[EADV] = N_("Advertise error"),
	[ESRMNT] = N_("Srmount error"),
	[ECOMM] = N_("Communication error on send"),
	[EPROTO] = N_("Protocol error"),
	[EMULTIHOP] = N_("Multihop attempted"),
	[EDOTDOT] = N_("Cross mount point"),
	[EBADMSG] = N_("Bad message"),
	[EFTYPE] = N_("Inappropriate file type or format"),
	[ENOTUNIQ] = N_("Name not unique"),
	[EBADFD] = N_("File descriptor in bad state"),
	[EREMCHG] = N_("Remote address changed"),
	[ELIBACC] = N_("Can not access a needed shared library"),
	[ELIBBAD] = N_("Accessing a corrupted shared library"),
	[ELIBSCN] = N_(".lib section in a.out corrupted"),
	[ELIBMAX] = N_("Attempting to link in too many libraries"),
	[ELIBEXEC] = N_("Attempting to exec a shared library"),
	[ENOSYS] = N_("Function not implemented"),
	[ENOTEMPTY] = N_("Directory not empty"),
	[ENAMETOOLONG] = N_("File or path name too long"),
	[ELOOP] = N_("Too many symbolic links"),
	[EOPNOTSUPP] = N_("Operation not supported on transport endpoint"),
	[EPFNOSUPPORT] = N_("Protocol family not supported"),
	[ECONNRESET] = N_("Connection reset by peer"),
	[ENOBUFS] = N_("No buffer space available"),
	[EAFNOSUPPORT] = N_("Address family not supported by protocol family"),
	[EPROTOTYPE] = N_("Protocol wrong type for socket"),
	[ENOTSOCK] = N_("Socket operation on non-socket"),
	[ENOPROTOOPT] = N_("Protocol not available"),
	[ESHUTDOWN] = N_("Can't send after socket shutdown"),
	[ECONNREFUSED] = N_("Connection refused"),
	[EADDRINUSE] = N_("Address already in use"),
	[ECONNABORTED] = N_("Connection aborted"),
	[ENETUNREACH] = N_("Network is unreachable"),
	[ENETDOWN] = N_("Network interface is not configured"),
	[ETIMEDOUT] = N_("Connection timed out"),
	[EHOSTDOWN] = N_("Host is down"),
	[EHOSTUNREACH] = N_("No route to host"),
	[EINPROGRESS] = N_("Connection already in progress"),
	[EALREADY] = N_("Socket already connected"),
	[EDESTADDRREQ] = N_("Destination address required"),
	[EMSGSIZE] = N_("Message too long"),
	[EPROTONOSUPPORT] = N_("Unknown protocol"),
	[ESOCKTNOSUPPORT] = N_("Socket type not supported"),
	[EADDRNOTAVAIL] = N_("Address not available"),
	[EISCONN] = N_("Socket is already connected"),
	[ENOTCONN] = N_("Socket is not connected"),
	[ENOTSUP] = N_("Operation not supported"),
	[EOVERFLOW] = N_("Value too large for defined data type"),
	[ECANCELED] = N_("Operation canceled"),
	[ENOTRECOVERABLE] = N_("State not recoverable"),
	[EOWNERDEAD] = N_("Previous owner died"),
	[ESTRPIPE] = N_("Streams pipe error"),
};

static char _error_string_unkown[100];
const char *strerror(int errnum) {
	if ((errnum >= 0 || (size_t)errnum < (size_t)sizeof(_error_strings) / sizeof(char *)) && _error_strings[errnum]) {
		return dgettext("tlibc", _error_strings[errnum]);
	} else {
		snprintf(_error_string_unkown, sizeof(_error_string_unknown), "%d", errnum);
		return _error_string_unkown;
	}
}
