name: build tlibc

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install gettext
      run: sudo apt install gettext

    - name: configure
      run: mkdir -p sysroot/usr && ./configure --prefix=./sysroot/usr --enable-shared

    - name: install headers
      run: make install-include

    - name: build
      run: make

    - name: install
      run: make install
