name: build tlibc

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install gettext
      run: sudo apt install gettext

    - name: Configure
      run: mkdir -p sysroot/usr build && cd build && ../configure --prefix=../sysroot/usr --enable-shared

    - name: Install headers
      run: make -C build install-include

    - name: Build
      run: make -C build

    - name: Install
      run: make -C build install
